CRAWLING_SPEED = 1
HOPPING_SPEED = 3
WALKING_SPEED = 4
RUNNING_SPEED = 6
FLYING_SPEED = 8

LEGS_NEEDED_CRAWL = 0
LEGS_NEEDED_HOP = 1
LEGS_NEEDED_RUN = 2
LEGS_NEEDED_WALK = 2
WINGS_NEEDED_FLY = 2

STAMINA_NEEDED_CRAWL = 0
STAMINA_NEEDED_HOPPING = 20
STAMINA_NEEDED_WALKING = 40
STAMINA_NEEDED_RUNNING = 60
STAMINA_NEEDED_FLYING = 80

POSITION_MIN = 0
POSITION_MAX = 100

CLAW_MIN = 0
CLAW_MAX = 2

LEG_MIN = 0
LEG_MAX = 5

WING_MIN = 0
WING_MAX = 3

TEETH_MIN = 0
TEETH_MAX = 2
